image: docker:latest

develop:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

    - docker build --build-arg http_proxy --build-arg https_proxy -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker rmi $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  only:
    - branches
  except:
    - master
  tags:
    - containers

latest:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

    - docker build --build-arg http_proxy --build-arg https_proxy -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - docker rmi $CI_REGISTRY_IMAGE
  only:
    - master
  tags:
    - containers
